// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-B9Eysxr32HzczgaH5uI4EoAQ47q-AA',
    appId: '1:335038769474:web:8e39f83b5bc66e066d00db',
    messagingSenderId: '335038769474',
    projectId: 'elective-triatlon',
    authDomain: 'elective-triatlon.firebaseapp.com',
    storageBucket: 'elective-triatlon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeiUcmvDEPabpTNyOrDf0usVXhLivBB7Y',
    appId: '1:335038769474:android:96164a027696f90c6d00db',
    messagingSenderId: '335038769474',
    projectId: 'elective-triatlon',
    storageBucket: 'elective-triatlon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6w1vYUDyDNvoxWVwgTKDIJe2vPp9MjGw',
    appId: '1:335038769474:ios:fb0438e36d3ad9a66d00db',
    messagingSenderId: '335038769474',
    projectId: 'elective-triatlon',
    storageBucket: 'elective-triatlon.appspot.com',
    iosClientId: '335038769474-s9cl8i2dnnonmv5rrrb4v9calstptd82.apps.googleusercontent.com',
    iosBundleId: 'com.example.elective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6w1vYUDyDNvoxWVwgTKDIJe2vPp9MjGw',
    appId: '1:335038769474:ios:fb0438e36d3ad9a66d00db',
    messagingSenderId: '335038769474',
    projectId: 'elective-triatlon',
    storageBucket: 'elective-triatlon.appspot.com',
    iosClientId: '335038769474-s9cl8i2dnnonmv5rrrb4v9calstptd82.apps.googleusercontent.com',
    iosBundleId: 'com.example.elective',
  );
}
